###############################
# Stage 1 - Build React
###############################

FROM node:20 AS frontend

WORKDIR /frontend

COPY frontend/package*.json ./

RUN npm install

COPY frontend .

RUN npm run build


###############################
# Stage 2 - Python Backend
###############################

FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY backend/requirements.txt .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

COPY backend .

COPY --from=frontend /frontend/dist ./dist

RUN mkdir -p uploads

EXPOSE 8000

CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]